/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p message_interface.h: ../shared/org.biohazard.message.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef MESSAGE_INTERFACE_H
#define MESSAGE_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.biohazard.message
 */
class OrgBiohazardMessageInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.biohazard.message"; }

public:
    OrgBiohazardMessageInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgBiohazardMessageInterface();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void message(const QString &base64);
};

namespace org {
  namespace biohazard {
    typedef ::OrgBiohazardMessageInterface message;
  }
}
#endif
